<?php

class ItonicsNabinTeacherController extends ItonicsNabinTeacherEntityBaseController
{

    public function __construct()
    {
        $this->baseEntityType = "itonics_nabin_teacher";
        parent::__construct();
    }

    /**
     * @param array $headers
     * @return mixed
     */
    public function listAll(array $headers = []): mixed
    {
        return db_select('itonics_nabin_teacher_information', 't')
            ->extend('PagerDefault')
            ->extend('TableSort')
            ->fields('t')
            ->limit(50)
            ->orderByHeader($headers)
            ->execute();
    }

    /**
     * @return void
     * @throws EntityMalformedException
     */
    public function populateSampleDataForStatesAndDistricts(): void
    {
        $stateController = entity_get_controller("itonics_nabin_state");
        $districtController = entity_get_controller("itonics_nabin_district");
        var_dump($districtController);
    }


    /**
     * @return ItonicsNabinTeacherEntity
     * @throws Exception
     */
    public function getNewTeacher(): ItonicsNabinTeacherEntity
    {
        $entity_default_data = [
            "teacher_id" => 0,
            "first_name" => "Hello",
            "last_name" => "Hallo",
            "gender" => "",
            "job_type" => serialize([]),
            "join_date" => REQUEST_TIME,
            "profile_picture" => 0,
            "description" => "",
            "created" => REQUEST_TIME,
            "changed" => REQUEST_TIME,
            "faculty_id" => 0,
        ];
        drupal_alter("itonics_nabin_teacher_entity_default_values", $entity_default_data);
        return new ItonicsNabinTeacherEntity($entity_default_data);
    }

    public function save($entity, DatabaseTransaction $transaction = NULL): bool|int|null
    {
        return parent::save($entity, $transaction); // TODO: Change the autogenerated stub
    }

    public function load($ids = array(), $conditions = array())
    {
        return parent::load($ids, $conditions); // TODO: Change the autogenerated stub
    }
}
